language: node_js
node_js:
- '6'
script:
- npm run lint
- npm test
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: t0GLfZHei4tE0ZfiHPoLBD0cjkFBPRLdpJJ9L4LNFJLBcnS4FoE1p3oCVUL1WoMCIjtPrdW3V6wiemggqbTxSZfA/aGEon2MrRU2H9YiRpeHCqHU0r2kAgGVhvE55ih/918FUHZENs98woJFtJMf8L54UCfc9QCd1FOkhctxyn8TEHlBYX0iO2sdz70+D0o8FGsoq8fS2Rvr9wnjrY8j9AwPz9uPEk/bntvphq4NRCHrdopbgeSGb6aR3QOlgD7nFmgqBQjuxqf/lP2YwR1HvywuJVKhRHPIDVNFQsOyQTMz4s8bweyXImx62ANY7wQ1O6WdVvtKwrv89N32iYuYHmlyHOfE6Dw2ryzunDmEPRjH6nHFiEzryZTvRimYWl567WKkDA7eHy8YxcdFJTqwsa53PlHFw91NHMupqaxc22L5xAcfFtlggw3CRTS6sYJgZxWcCNGzL1L/utzawmZ+9u54tlWb80XtN/PVgBukgdkUzgsfI2FHjA3CJXPfyYeSm666Z4y/OT4V//0zA1nBeeMlVkmVZz/SCsQAFG1M7IzqcJ9HULzIJL6xSldpSSsOAhtl7ynPyUQ1WVqSiZisIuL9pNmEhhqajgIZNug8sawkTlE2KqZNOJ57CdGVijqQB3C1m3A5u839Jfm7GS0V/lCH5KRNLLIp1L7vnIQc9Bg=
