---
parameters:
  authorizationHeader:
    in: header
    name: authorization
    description: Authorization token.
    required: true
    type: string
definitions:
  bodyArticle:
    type: object
    description: Article body.
    properties:
      content:
        type: string
        description: The content of the article to transform.
        example: <section>some text</section>
      title:
        type: string
        description: Article title.
        example: test
      introduction:
        type: string
        description: Article introduction.
        example: intro
      metaDescription:
        type: string
        description: Meta description of the article contents.
        example: meta description here
  copyright:
    type: object
    description: Copyright attributes.
    properties:
      license:
        type: object
        description: License information.
        properties:
          license:
            type: string
            description: License short name.
            example: by-sa
          description:
            type: string
            description: License full name.
            example: Creative Commons Attribution-ShareAlike 2.0 Generic
          url:
            type: string
            description: URL to full license documentation.
            example: https://creativecommons.org/licenses/by-sa/2.0/
      origin:
        type: string
        description: Copyright origin.
      creators:
        type: array
        description: Creators.
        items:
          type: object
          properties:
            type:
              type: string
              description: Creator type
              example: Writer
            name:
              type: string
              description: Creator name
              example: John Doe
      processors:
        type: array
        description: Processors.
        items:
          type: object
          properties:
            type:
              type: string
              description: Processors type
              example: Supplier
            name:
              type: string
              description: Processors name
              example: John Doe
      rightholders:
        type: array
        description: Rightholders.
        items:
          type: object
          properties:
            type:
              type: string
              description: Rightholders type
              example: Owner
            name:
              type: string
              description: Rightholders name
              example: John Doe
  h5p:
    type: object
    description: H5P attributes
    properties:
      title:
        type: string
        description: H5P title
        example: Foo
      license:
        type: string
        description: License short name
        example: CC BY-SA
      licenseVersion:
        type: string
        description: License version
        example: 4.0
      thumbnail:
        type: string
        description: Thumbnail URL
        example: https://test.api.ndla.no/image-api/raw/tacf8f02.jpg
      contentType:
        type: string
        description: Content type
        example: Image
      authors:
        type: array
        description: Authors
        items:
          type: object
          properties:
            name:
              type: string
              description: Author name
              example: John Doe
            type:
              type: string
              description: Author type
              example: Author
